In [1]:
# Letâ€™s make use of PyMongo to interact with MongoDb and insert a document.
from pymongo import MongoClient

# Create a client connection to the MongoDb instance running on the local machine
client = MongoClient('localhost:27017')

# Defining a database object to insert data into the MongoDb database.
db = client.EmployeeData

 
# Function to insert data into mongo db
def insert():
    try:
        employeeId = input('Enter Employee id :')
        employeeName = input('Enter Name :')
        employeeAge = input('Enter age :')
        employeeCountry = input('Enter Country :')
        # Inserts a document to a collection called Employee
        db.Employees.insert_one(
            {
                "id": employeeId,
                "name":employeeName,
                "age":employeeAge,
                "country":employeeCountry
            })
        print('\nInserted data successfully\n')
    
    except Exception as e:
        print(str(e))

# Function to delete record from mongo db
def delete():
    try:
        criteria = input('\nEnter employee id to delete\n')
        # Removes all documents that match the filter from a collection.
        db.Employees.delete_many({"id":criteria})
        print('\nDeletion successful\n') 
    except Exception as e:
        print(str(e)) 

# function to read records from mongo db
def read():
    try:
        # Selects documents in a collection or view and returns a cursor to the selected documents.
        empCol = db.Employees.find()
        print('\n All data from EmployeeData Database \n')
        for emp in empCol:
            print(emp)

    except Exception as e:
        print( str(e))

# Function to update record to mongo db
def update():
    try:
        criteria = input('\nEnter id to update\n')
        name = input('\nEnter name to update\n')
        age = input('\nEnter age to update\n')
        country = input('\nEnter country to update\n')
        # update_one: Update a single document matching the filter.
        # The $set operator replaces the value of a field with the specified value.
        db.Employees.update_one
        (
            {"id": criteria},
            {
            "$set": {
                "name":name,
                "age":age,
                "country":country
            }
            }
        )
        print("\nRecords updated successfully\n")    
    
    except Exception as e:
        print (str(e))

def main():

    while(1):
        # chossing option to do CRUD operations
        selection = input('\nSelect 1 to insert, 2 to update, 3 to read, 4 to delete\n')
    
        if selection   ==  '1':
            insert()
        elif selection == '2':
            update()
        elif selection == '3':
            read()
        elif selection == '4':
            delete()
        else:
            print('\n INVALID SELECTION \n')    
            break

In [2]:
main()

Select 1 to insert, 2 to update, 3 to read, 4 to delete
3

 All data from EmployeeData Database

{'_id': ObjectId('5b534d0d23526450f400eca7'), 'id': '1', 'name': 'Dinesh', 'age': '19', 'country': 'India'}
{'_id': ObjectId('5b534d7423526450f400ecaa'), 'id': '2', 'name': 'Niranjan', 'age': '27', 'country': 'America'}

Select 1 to insert, 2 to update, 3 to read, 4 to delete
5

 INVALID SELECTION